services:
  - type: web
    name: trust-prediction
    runtime: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install numpy==1.24.4
      pip install -r requirements.txt
    startCommand: python app.py
